config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get 'about' => 'welcome#about'

  get 'info' => 'welcome#info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coding Bootcamp Experience</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">


    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">


	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    
  </head>


<body>
	<!-- NAVBAR -->

	<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">coding bootcamp</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Home", root_path %> </li>
		      <li> <%= link_to "About", about_path %> </li>
		      <li> <%= link_to "Helpful Info", info_path %> </li>
		    </ul>
        </div>
      </div>
    </nav>


    <%= yield %>


  </body>
</html>

app/views/welcome/about.html.erb
<div class="jumbotron aboutjumbo jumbotron-fluid vertical-center">
  <div class="container">
    <h1 class="featurette-heading text-center"> meet the students </h1>
    <p class="lead">| &nbsp; michelle bilich &nbsp;|&nbsp; jared jones &nbsp; |</p>
  </div>
  </div>
  <div class="container">

<!-- Left-aligned -->
<div class="container marketing">
<hr class="featurette-divider">
 <div class="featurette">
   <img class="featurette-image img-circle img-responsive pull-right" <%=image_tag("Jared2.jpg")%>
   <h2 class="featurette-heading">Jared Jones</h2>
   <ul class="lead">
     <li>Grew up in Middletown, Ohio</li>
      <li>After graduation I attended The Ohio State University</li>
      <li>Graduated from OSU with a B.S. in Turfgrass Science</li>
      <li>Spent 2 Years upon graduation as a Golf Professional in Central Ohio</li>
      <li>Transitioned into sales in the Insurance industry for almost a decade</li>
      <li>Left the Insurance industry to start a local retail business with some friends</li>
      <li>A few years later I decided retail wasn't for me and technology would be my next path</li>
      <li>Enrolled in Tech Talent South Code Immersion Bootcamp</li>
   </ul>
 </div>
 <hr class="featurette-divider">
 <div class="featurette">
   <img class="featurette-image img-circle img-responsive pull-left" <%=image_tag("headshot.jpg")%>
      <h2 class="featurette-heading">Michelle Bilich</h2>

      <ul class="lead">
     <li>Born in New Orleans but grew up in Southwest Florida.</li>
      <li>Family business Co-Owner/Operator at Cell-Tech Express (electronic repair and retail stores)</li>
      <li>No previous programming experience prior to attending bootcamp besides some basic HTML and CSS knowledge</li>
      <li>Reason for attending bootcamp: To implement what I've learned into our current business model to solve various problems and become more efficient.</li>
      <li>Goals after bootcamp: To continue learning more about Ruby on Rails, Python and Javascript. As well as learning to build and program using raspberry pi.</li>
   </ul>
 </div>
 <hr class="featurette-divider">

app/views/welcome/home.html.erb
<!-- JUMBOTRON -->
<div class="jumbotron jumbotron-fluid vertical-center">
  <div class="container">
    <h1 class="featurette-heading text-center"> hello world. </h1>
    <p class="lead">two coding bootcamp students <br>make a website</p>
  </div>
</div>


<!-- Wrap to center all the content. -->
<div class="container marketing">

<hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle img-responsive pull-right" <%=image_tag("TTS_classmates.jpg")%>
    <h2 class="featurette-heading text-center"> BOOTCAMP <br><span class="text-muted text-center"> <i>what did we learn?</i> </span></h2>

    <br>

<!-- START RUBY, RAILS, DOMAIN MODELING ETC DESCRIPTIONS -->

  <div class="row-fluid-wrapper row-depth-1 row-number-5 ">
  <div class="row-fluid ">
  <div class="span12 widget-span widget-type-widget_container " style="" data-widget-type="widget_container" data-x="0" data-w="12">

  <div class="custom-three-col-content-box clearfix">
      <div class="row">
          <div class="col-sm-4 col-md-4 custom-col1">
              <div class="content-boxes style-two top-column clearfix animated zoomInLeft wow">
                  <div class="content-boxes-text">
                      <h4 class="featurette-heading">Ruby</h4>
  <p class="lead">One of the most popular object oriented programming languages, Ruby! It's powerful, yet simple syntax got us programming in no time!</p>
                  </div>
              </div>
          </div>
          <div class="col-sm-4 col-md-4 custom-col2">
              <div class="content-boxes style-two top-column clearfix animated zoomInLeft wow">
                  <div class="content-boxes-text">
                      <h4 class="featurette-heading">Rails</h4>
  <p class="lead">Ruby on Rails, this versatile web application framework that allows for rapid prototyping of database driven apps.</p>
                  </div>
              </div>
          </div>
          <div class="col-sm-4 col-md-4 custom-col3">
              <div class="content-boxes style-two top-column clearfix animated zoomInLeft wow">
                  <div class="content-boxes-text">
                      <h4 class="featurette-heading">HTML/CSS</h4>
  <p class="lead">We produced structure and content with HTML, then made it beautiful and responsive with CSS.</p>
                  </div>
              </div>
          </div>
      </div>
  </div></div>
      <div class="row">
          <div class="col-sm-4 col-md-4 custom-col1">
              <div class="content-boxes style-two top-column clearfix animated zoomInLeft wow">
                  <div class="content-boxes-text">
                      <h4 class="featurette-heading">APIs</h4>
  <p class="lead">Our apps use external APIs that pulled in data from sources like Google Maps, Stripe, and Facebook.</p>
                  </div>
              </div>
          </div>
          <div class="col-sm-4 col-md-4 custom-col2">
              <div class="content-boxes style-two top-column clearfix animated zoomInLeft wow">
                  <div class="content-boxes-text">
                      <h4 class="featurette-heading">Deployment</h4>
  <p class="lead">We wanted to share them with the world! Heroku helped us deploy apps and make it live for others to use.</p>
                  </div>
              </div>
          </div>
          <div class="col-sm-4 col-md-4 custom-col3">
              <div class="content-boxes style-two top-column clearfix animated zoomInLeft wow">
                  <div class="content-boxes-text">
                      <h4 class="featurette-heading">Domain Modeling</h4>
  <p class="lead">While working with Rails, we learned the crucial skill of modeling resources and relationships in database backed web apps.</p>
                  </div>
              </div>
          </div>
      </div>
  </div></div></span>



  <hr class="featurette-divider">


  <div class="featurette">
    <img class="featurette-image img-circle img-responsive pull-left" src="https://images.unsplash.com/photo-1518818608552-195ed130cdf4?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;s=f4df39ab3b871f8c91b795b1c1e6ac3c">
       <h2 class="featurette-heading">RoR <span class="text-muted"> focus </span></h2>
    <p class="lead">Ruby on Rails was the primary focus in our bootcamp. This language and framework has it's complexities like any other programming language, but due to it being somewhat newer it has enough support and community built up to make it a great first language and framework to learn. Since it's inception in 2005 many have fallen in love with it's ability to provide industry standards. </p>
  </div>



  <hr class="featurette-divider">


  <div class="featurette">
    <img class="featurette-image img-circle img-responsive pull-right" src="https://images.unsplash.com/photo-1520085601670-ee14aa5fa3e8?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;s=5707340857e74a0a99e728905a6576e4">
      <h2 class="featurette-heading">Coders <span class="text-muted"> Wanted </span></h2>
    <p class="lead">Industries rise and fall as new technologies emerge, but programmers and developers will always be needed. There will always be problems to solve and overcome, which is why a human element will continue to be required. It is the empathetic ability of humans to see when something new should be created that will keep them coding.</p>
  </div>
  <hr class="featurette-divider">

</div>

  <!-- /END THE FEATURETTES -->

  <!-- START TESTIMONIALS -->

  <h1 class="featurette-heading testtitle text-muted">why do you code?</h1>
  <br>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="carousel slide" data-ride="carousel" id="quote-carousel">
      
<!-- Bottom Carousel Indicators -->
<ol class="carousel-indicators">
  <li data-target="#quote-carousel" data-slide-to="0" class="active"></li>
  <li data-target="#quote-carousel" data-slide-to="1"></li>
  <li data-target="#quote-carousel" data-slide-to="2"></li>
</ol>
        
<!-- Carousel Slides / Quotes -->
<div class="carousel-inner">

    <!-- Quote 1 -->
    <div class="item active">
      <div class="row">
        <div class="col-sm-12">
          <p class="quote">&ldquo;Coding is interesting and fun. The possibilities are endless. Coding is a wonderful thing that I think most people should do everyday.&rdquo;</p>
          <small><strong>Mark Akom</strong></small>
        </div>
      </div>
    </div>

    <!-- Quote 2 -->
    <div class="item">
      <div class="row">
        <div class="col-sm-12">
          <p class="quote">&ldquo;Although it's tough to learn, stick with it! The benefits are great! :)&rdquo;</p>
          <small><strong>Manish Singh</strong></small>
        </div>
      </div>
    </div>

    <!-- Quote 3 -->
    <div class="item">
      <div class="row">
        <div class="col-sm-12">
          <p class="quote">&ldquo;Programming not only gives you freedom to solve problems and build things, it gives you power! &rdquo;</p>
          <small><strong>Abel Wharton</strong></small>
        </div>
      </div>
    </div>
</div>
<br>

<hr class="featurette-divider">

       

app/views/welcome/info.html.erb
<div class="jumbotron infojumbo jumbotron-fluid vertical-center">
  <div class="container">
    <h1 class="featurette-heading text-center"> helpful information</h1>
    <p class="lead">links to websites, events, acticles, blogs etc</p>
  </div>
</div>


<div class="container marketing">

<hr class="featurette-divider">
 <div class="featurette">
   <a href="https://www.meetup.com/" target="blank"><img class="featurette-image img-circle img-responsive pull-right" <%=image_tag("Meetup.jpg")%></a>
   <h3 class="featurette-heading">Meetup</h3>
   <ul class="lead">
     <li>On your journey you are going to find out that networking is very important!</li>
     <li>At Meetups in the tech community you will find tons of topics in your area of interest.</li>
     <li>Most importantly you get to meet great like minded folks who are there to learn, mentor and mingle with new people in the industry.</li>
     <li>The food and drinks are pretty nice too!</li>
   </ul>
 </div>







<hr class="featurette-divider">
 <div class="featurette">
  <a href="https://teamtreehouse.com" target="_blank"><img class="featurette-image img-circle img-responsive pull-left" <%=image_tag("Treehouse-Logo.jpg")%></a>

   <h3 class="featurette-heading">Treehouse</h3>
   <ul class="lead">
     <li>Check out Treehouse for great videos of instruction when concepts get rough!</li>
     <li>There are free trials and monthly subscriptions at $25/month or actual degree/certification options.</li>
   </ul>
 </div>

 <hr class="featurette-divider">
 <div class="featurette">
   <a href="https://www.w3schools.com" target="_blank"><img class="featurette-image img-circle img-responsive pull-right" <%=image_tag("W3Schools.jpg")%></a>
   <h3 class="featurette-heading">w3schools.com</h3></a>
   <ul class="lead">
     <li>w3schools.com is a great resource for all of your HTML, CSS, Bootstrap, JavaScript, SQL needs!</li>
     <li>Here we found many helpful sections where it makes things easy when copying/pasting sections of code to try in your projects.</li>
   </ul>
 </div>
 <hr class="featurette-divider">
 <div class="featurette">
   <a href="https://www.youtube.com" target="_blank"><img class="featurette-image img-circle img-responsive pull-left" <%=image_tag("Youtube.jpg")%></a>
   <h3 class="featurette-heading">YouTube</h3>
   <ul class="lead">
     <li>YouTube as everyone knows has become the new, "Google it!" phrase for folks looking to do things.</li>
     <li>We found it's no different with some of the concepts we learned in class.</li>
     <li>You may even run into a motivational video to keep you going!</li>
   </ul>
 </div>
 <hr class="featurette-divider">
 <div class="featurette">
   <a href="https://www.stackoverflow.com" target="_blank"><img class="featurette-image img-circle img-responsive pull-right" <%=image_tag("StackOverflow.jpg")%></a>
   <h3 class="featurette-heading">StackOverflow</h3>
   <ul class="lead">
     <li>Get an error?? You will likely find this resource very helpful to fix those bugs.</li>
     <li>When Googling one's way to success we found StackOverflow as the greatest help!</li>
     <li>This place has it all and is one of the largest communities online with vast resources and helpful folks.</li>
   </ul>
 </div>